---
title: 
  ru: "Оценка открытости, доступности и достоверности экологической информации о выбросах диоксида серы в 31 населённом пункте России с помощью данных дистанционного зондирования Земли"
  en: ""
author:
  ru: "Сёмин Павел Олегович"
  en: "Pavel O. Syomin"
abstract:
  ru: ""
  en: ""
keywords:
  ru: ""
  en: ""
udk_code: ""
output:
  odt_document:
    reference_odt: reference-styles.odt
    template: template.opendocument
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(knitr)
```

# 1. Введение

Право на достоверную информацию о состоянии окружающей среды — одно из базовых экологических прав человека. Оно закреплено в статье 42 Конституции России, раскрывается в федеральном законе от 10 января 2002 года №7-ФЗ «Об охране окружающей среды» и дополнительно регламентируется в подзаконных актах. На международном уровне важное значение в признании и регулировании этого права имеет Конвенция о доступе к информации о состоянии окружающей среды 1998 года (Орхусская конвенция). Право на доступ к информации о состоянии окружающей среды пересекается с правом на доступ к информации о деятельности органов государственной власти, перекликается с принципом информационной открытости государства, направлено на обеспечение экологического просвещения, способствует осознанному участию граждан и их объединений в решении вопросов, касающихся окружающей среды. Открытость, доступность и достоверность экологической информации не только является приоритетом современной государственной экологической политики, но и становится частью экологической политики крупных компаний-природопользователей, которые самостоятельно раскрывают нефинансовую информацию, в том числе информацию об использовании природных ресурсов и своём воздействии на окружающую среду.

Важными требованиями, предъявляемыми к экологической информации, являются её открытость, доступность и достоверность. Конечно, это далеко не все требования к такой информации, однако это именно те, которые имеют наибольшее значение. Открытость информации характеризует саму возможность получить доступ к информации, доступность относится к простоте получения информации, а достоверность означает, насколько доступная информация отражает реальное положение вещей. Все эти характеристики имеют большое значение, когда речь идёт об информации в сфере окружающей среды: если информация закрыта, то это нарушает право на доступ к экологической информации, если она открыта, но труднодоступна, то реализация права затрудняется, а недостоверность имеющейся информации сводит на нет её ценность и фактически тоже приводит к тому, что право на достоверную информацию о состоянии окружающей среды не реализуется.

Современные стандарты информационной открытости предполагают, что общественно значимая информация должна находиться в открытом доступе. Иначе говоря, с позиций закона «Об информации, информационных технологий и о защите информации», такая информация должна не предоставляться, а распространяться. Наиболее удобный способ распространения такой информации — размещение её на сайте в Интернете. Более того, предпочтительным в настоящее время является размещение информации в формате открытых данных, то есть в виде, пригодном для автоматизированной обработки. В то же время довольно очевидно, что в отношении экологической информации это требование реализуется далеко не всегда. Возникает вопрос: насколько открытой и доступной является экологическая информация в России с учётом современных стандартов открытости и доступности информации?

Аналогичные вопросы возникают по отношению к достоверности официальной экологической информации в России. Несмотря на то что утверждение о систематической искажении экологической информации в России было бы слишком голословным, очевидно, что далеко не всегда имеющаяся информация отражает реальное состояние окружающей среды и реальное воздействие на неё. Причины этого могут быть как объективные — трудоёмкость получения необходимой информации и как следствие, отсутствие актуальных данных, неточность измерений, несовершенство методики сбора данных — так и субъективные в виде искажения экологической отчётности. Независимо от причины, актуальным становится вопрос о том, как можно проверить достоверность официальной экологической информации.

Для проверки как степени открытости и доступности, так и достоверности экологической информации наиболее очевидный путь — сравнить информацию из разных источников. Информация о состоянии и о загрязнении окружающей среды может быть получена разными способами. Традиционный способ — это агрегирование данных статистической отчётости природопользователей, также известный как bottom-up inventories (подразумевается, что движение информации идёт снизу вверх: от данных по отдельным источникам загрязнения к статистике по городам, регионам, странам). Альтернативный способ — использование данных дистанционного зондирования. Этот способ появился в 80-90-е годы XX века в связи с развитием космических технологий и появлением спутников, способных осуществлять дистанционный мониторинг происходящего на поверхности Земли. Поначалу он использовался исключительно в экспериментальных целях, но по мере совершенствования технологий стал дополнять, а в ряде случаев и заменять наземные данные. В частности, использование дистанционных технологий для контроля за состоянием и загрязнением окружающей среды является единственным вариантом в случае крупных естественных источников выбросов, таких как вулканы. В то же время спутниковые данные могут использоваться и для проверки результатов наземных измерений, особенно в случаях, когда доступ к информации, полученной bottom-up-методом, затрудён. В частности, дистанционные методы широко используются для контроля за изменением выбросов в воздух с территории Китая и Индии и позволяют, в частности, отследить внедрение новых более экологически чистых технологий или экономические спады, которые приводят к снижению выбросов тех или иных загрязняющих веществ. В последние годы стали появляться отдельные примеры, когда данные дистанционного зондирования используются непосредственно для проверки достоверности официальной экологической отчётности. В частности, авторы одного исследования пришли к выводу о систематическом занижении отчётности о выбросах в Мексике. Для России аналогичного исследования не проводилось, однако авторы разных статей, посвящённых дистанционному мониторингу выбросов в атмосферу, осторожно отмечают, что существуют расхождения между отчётными данными по России и данными, полученными с помощью космического мониторинга, и эти различия выражаются в том, что отчётные данные оказываются несколько меньше. В то же время существует одна работа, в которой сравнивались данные о выбросах диоксида серы в Норильске, полученные из отчётности и по спутниковым снимкам, и авторы пришли к выводу о том, что отчётные и дистанционные результаты хорошо согласуются друг с другом. Такая ситуация повышает актуальность вопроса о проверке официальной экологической информации о выбросах на территории России с помощью данных спутникового мониторинга.

Необходимо отметить, что вопрос об использовании данных космического мониторинга в юридических целях не является совсем уж новым в российской научной литературе. В частности, отмечается, что данные дистанционного зондирования на протяжении примерно 20 лет используются для государственного мониторинга земель, то есть для реализации одной из функций управления в сфере охраны окружающей среды. Важное значение дистанционные технологии имеют при определении незаконных рубок лесных насаждений, то есть для выявления, пресечения и раскрытия преступлений. Предлагается использовать данные космического мониторинга в рамках договоров страхования в сельскохозяйственной сфере для определения размера платежей по договору и факта наступления страхового случая. Спутниковые снимки довольно давно используются экспертами Минюста России для проведения судебно-экологических экспертиз. Таким образом, можно поставить вопрос и об использовании данных дистанционного зондирования в контексте права на доступ к достоверной информации о состоянии окружающей среды — для оценки того, насколько соблюдаются юридически значимые требования к такой информации.

Право на доступ к экологической информации многогранно. Обычно в него включют как минимум право на доступ к информации о состоянии окружающей среды и к информации об антропогенном воздействии на окружающую среду. Охватить все виды экологической информации в рамках одной статьи невозможно по двум причинам: во-первых, это сделает статью крайне объёмной, а во-вторых, далеко не всегда имеются альтарнативные источники для сравнения. В данной статье рассматривается только информация о выбросах диоксида серы в атмосферный воздух в 31 населённом пункте на территории России. Выбор связан преимущественно с тем простым фактом, что для выбросов дикосида серы в атмосферный воздух есть глобальный каталог данных, полученных с помощью дистанционного зондирования и представленных в удобном виде — выбросов по крупнейшим источникам загрязнения за 2005–2019 годы в тысячах тонн в год. Для других загрязняющих веществ подобные каталоги автору статьи неизвестны. Кроме того, поскольку сравнение данных будет осуществляться количественными методами, гораздо правильнее не расширять предмет статьи, а напротив, максимально сузить его, сведя к только одному загрязняющему веществу. Диоксид серы является одним из ключевых компонентов антропогенных выбросов и одним из целевых загрязняющих веществ при мониторинге, поэтому информацию о его выбросах можно характеризовать как достаточно важную, а сам показатель «объём выбросов диоксида серы» — как достаточно характерный, позволяющий с некоторой осторожностью даже сделать предположения об открытости, доступности и достоверности экологической информации в целом.

Основная идея исследования заключается в том, чтобы сравнить информацию о выбросах дикосида серы в России, полученную из двух источников: официальная отчётность и данные дистанционного зондирования Земли. Каждый такой источник информации можно характеризовать с позиции открытости, доступности и достоверности информации, при этом открытость и доступность будут относиться к простоте получения информации из данного источника, а достоверность — к данным, которые представлены в этом источнике. Сравнение позволит оценить открытость, доступность и достоверность экологической информации о выбросах диоксида серы в 31 населённом пункте России, что является целью исследования. Для решения данной цели выполняются следующие задачи:

1) получить массивы данных для сравнения: массив данных, подготовленных с помощью космического мониторинга, и массив данных, содержащихся в официальной отчётности;

2) сравнить массивы данных с точки зрения наличия необходимой информации и процедуры получения;

3) сравнить данные, содержащиеся в массивах;

4) дать юридическую интерпретацию результатов сравнения и сделать предположения о перспективах использования дистанционных данных для оценки открытости, доступности и достоверности экологической информации с учётом результатов исследования.

Исследование, таким образом, с одной стороны носит конкретный характер и заключается в сравнении двух массивов данных с точки зрения процедуры их получения и качества самих данных, а с другой стороны, является примером того, как можно на практике использовать данные дистанционного зондирования при работе с экологической информацией для реализации права каждого на доступ к такой информации.

Перед тем как перейти к основному исследованию, нужно сделать одно важное замечание. Поскольку открытость, доступность и достверность информации являются юридически значимыми характеристиками экологической информации, отступление от них (сокрытие или искажение информации) является правонарушением. В связи с этим велик соблазн рассматривать дистанционные данные в первую очередь с точки зрения выявления правонарушений. Поскольку в данной статье будут использоваться данные о выбросах в конкретных населённых пунктов, а в некоторых случаях — с конктерных источников, то возникает риск того, что статья будет восприниматься как расследование. Однако автору не хотелось бы, чтобы статья воспринималась как попытка уличить отдельные организации или органы власти в умышленном искажении информации о выбросах в атмосферный воздух. Конечно, из исходных данных в любом случае можно будет сделать определённые выводы в том числе о конкретных организациях и территориях, однако в общем и целом исследование направлено не на то, чтобы заподозрить нарушения, а на то, чтобы обрисовать общую картину открытости, доступности и достоверности экологической информации, а главное — предупредить от слишком поспешных выводов и указать на тонкости, нюансы и подводные камни, которые могут возникнуть при сравнении наземных данных с дистанционными в юридических целях. Поэтому результаты исследования в статье представлены суммарно по стране без разбивки по субъектам Российской Федерации и городам, предпочтение отдаётся положительным примерам, а при обсуждении результатов отдельно отмечается многообразие причин расхождений между наземными и дистанционными данными, большая часть из которых не связана с правонарушениями.

# 2. Основное исследование

## 2.1. Получение данных для сравнения

В исследовании используются два набора данных о выбросах диоксида серы. Первый основан на данных дистанционного зондирования, второй — на официальной отчётности. Наборы данных были получены по-разному.

Набор данных о выбросах, составленный с помощью космического мониторинга, был взят с сайта проекта «Global Sulfur Dioxide Monitoring», который организован НАСА. Сами данные находятся на странице https://so2.gsfc.nasa.gov/measures.html. Они представлены в нескольких вариантах, в частности табличном и картографическом. Для исследования был использован табличный вариант.

Набор дистанционных данных представляет собой каталог из 634 источников выбросов, расположенных по всему миру. Каталог включает крупнейшие источники выбросов диоксида серы — те, ежегодные выбросы от которых превышают примерно 30 тысяч тонн. Менее крупные источники в каталог не включены, поскольку меньший объём выбросов затруднительно отследить со спутников. Источники в каталоге сгруппированы по типам и странам. Выделяются четыре типа источников, три из которых являются антропогенными: электростанции, металлургические производства, нефтегазовые производства. Россия в каталоге представлена 31 антропогенным источником. Как правило, источник выбросов — это либо крупный промышленный центр с одним или несколькими крупными промышленными предприятиями. Для каждого источника в каталоге указан объём выбросов диоксида серы за каждый год с 2005 по 2019.

Научно-теоретическую основу каталога представляет собой работа международной группы исследователей, результаты который изложены в статье (Фиолетов, 2016). Именно в этой статье была представлена первая версия каталога с данными до 2014 года включительно. В заключительном разделе данной статьи авторы выразили надежду, что первая версия каталога будет дополнена и обновлена, и обновлённая версия будет размещена на сайте НАСА по указанному выше адресу. Насколько можно судить, именно так и произошло.

Два каталога: прикреплённый к статье и размещённый на сайте НАСА — различаются. Каталог, прикреплённый к оригинальной статье, охватывает период только по 2014 год и содержит меньше источников выбросов. Каталог на сайте содержит хронологию выбросов по 2019 год и включает дополнительные источники выбросов. Конкретные объёмы выбросов по годам в каталогах также различаются: если сравнить данные с 2005 по 2014 год из двух каталогов по одному и тому же источнику выбросов, то точных совпадений почти нет. Скорее всего, расхождение связано с тем, что каталоги получены на основе одних и тех же дистанционных данных и с помощью одного и того же алгоритма, но с разными настройками алгоритма. О том, что настройки алгоритма существенно сказываются на результатах, говорят и авторы оригинальной статьи. Для данного исследования был взят более новый каталог — по 2019 год с сайта НАСА. Тем не менее, оригинальная статья учитывалась, когда возникал вопрос о точности данных, представленных в каталоге, о чём будет говориться дальше.

В отличие от данных дистанционного зондирования, для данных официальных отчётности единый каталог отсутствует, поэтому автор статьи собирал его самостоятельно. В качестве шаблона для каталога использовался дистанционный каталог. Было внесено только одно изменение: источники выбросов Nickel (пгт Никель в Мурманской области) и Severonikel (посёлок Мончегорск в Мурманской области) были объединены в один. Это связано с тем, что предприятия, дающие основную массу выбросов диоксида серы в данных населённых пунктах, принадлежат Кольской горно-металлургической компании в составе «Норникеля», поэтому в корпоративной отчётности «Норникеля» указаны суммарные выбросы диоксида серы по этим двум источникам. Поскольку корпоративная отчётность представляла собой довольно ценный источник информации, и альтернативы ей в данном случае отсутствовали, было решено объединить данные по двум источникам выбросов, чтобы повысить полноту набора информации. Соответственно данные были объединены и в каталоге по спутниковым измерениям. В итоге собирались данные по 30 источникам выбросов за 2005–2019 годы, то есть всего 450 значений.

В качестве источников официальной информации использовались следующие:

1) данные официальной статистики, опубликованные на сайте Росстата. Как правило, бралась информация из «Базы данных показателей муниципальных образований». Например, в базе данных показателей муниципальных образований по Свердловской области можно найти информацию о выбросах диоксида серы от стационарных источников на территории муниципального образования «Кировградский городской округ» за 2014–2017 годы;

2) данные государственных докладов о состоянии и охране окружающей среды или аналогичных докладов, подготовленных органами государственной власти субъекта, на территории которого расположен источник выбросов. Например, в государственных докладах о состоянии и об охране окружающей среды в Оренбургской области есть информация о выбросах диоксида серы за 2005–2009 годы в Оренбурге;

3) сводные данные по форме статистической отчётности 2-ТП (воздух) в разрезе субъектов и муниципальных образований, размещённые на сайте Росприроднадзора. Например, в этих сводных данных есть информация о выбросах диоксида серы в Новокуйбышевске (Самарская область) за 2018–2019 годы;

4) данные корпоративной отчётности крупных компаний, владеющих источниками выбросов. Например, из отчётов об устойчивом развитии компании «Норникель» можно извлечь данные о выбросах диоксида серы в Норильске за большую часть лет с 2007 по 2019 год. В качестве корпоративной отчётности рассматривались только полноценные отчёты, а не краткая информация о воздействии на окружающую среду, размещённая, например, в виде пресс-релизов или общих сведний.

Поскольку почти ни для каких источников выбросов нет такого источника информации, который содержал бы данные за все годы, итоговая таблица формировалась как смесь сведений из разных источников. Так, в «Базе данных показателей муниципальных образований» содержалась информация о выбросах диоксида серы для всех источников, но только за 2014–2017 годы, а в нескольких случаях даже за меньший промежуток времени. Сводная статистика по формам 2-ТП (воздух) тоже охватывает все источники выбросов, однако есть только для 2018 и 2019 года. Государственные доклады обычно имеются за более продолжительный период времени (иногда с конца 1990-х), однако сильно различаются по информационному наполнению, и не для всех источников выбросов в этих докладах есть сведения об объёме выбросов. Корпоративная отчётность охватывает разные периоды времени и есть только у двух компаний. Таким образом, при составлении каталога объёмов выбросов по данным официальной отчётности использовалась любая доступная официальная информация. В тех случаях, когда для одного и того же года для одного и того же источника выбросов было доступно несколько значений объёма выбросов (например, из Росстата и государственного доклада), они усреднялись, за исключением тех случаев, когда какое-то одно значение было в десятки раз меньше других и выглядело как ошибка — тогда оно просто не учитывалось.

В конечном итоге для каждого источника выбросов удалось найти информацию о выбросах диоксида серы хотя бы за какие-то годы, однако протяжённость хронологии для разных источников выбросов отличается и составляет от 6 до 15 лет. Из 450 искомых значений удалось найти 251, то есть чуть больше половины. Несмотря на такую неполноту данных по официальной отчётности, 251 измерение — достаточное количество для статистического анализа. Возможно, какую-то часть недостающей информации можно было бы получить в порядке предоставления путём направления запросов в Росстат, однако нет гарантии, что это даст нужный результат. Кроме того, учитывая, что современные стандарты открытости предполагают возможность доступа к данным, размещённым в Интернете, автор целенаправленно отказался от варианта направления запросов в органы государственной власти, поскольку сама необходимость направлять запросы уже означает, что доступность информации находится не на самом высоком уровне.

Необходимо сделать ещё два комментария по поводу сбора отчётных данных. Первая особенность связана с тем, что источники выбросов в каталоге по дистанционным данным привязаны к конкретным районам на поверхности Земли, в то время как официальная отчётность даётся по населённым пунктам, муниципальным образованиям или предприятиям. Следовательно, возникает принципиальный методологический вопрос: как соотнести дистанционные данные, которые по сути говорят о выбросах диоксида серы с конкретной территории, с данными отчётов? Сложность в том, что у спутниковых наблюдений ограниченная точность, и несколько разных источников выбросов в радиусе примерно 50 километров из космоса детектируются как один источник. Авторы оригинального каталога использовали всю имеющуюся у них информацию о сколько-нибудь существенных наземных источниках выбросов, чтобы соотнести дистанционные данные с конкретным источником, и давали названия источникам выбросов по названию населённого пункта. Например, выбросы в районе с координатами, соответствующими Москве, в каталоге были отмечены как «Москва». В подавляющем большинстве случаев для обратного соотнесения — дистанционных данных с официальной отчётностью — было достаточно взять соответствующий город или муниципальный район, а в случае с Москвой — весь субъект федерации. Однако в редких случаях приходилось складывать объёмы выбросов в соседних муниципальных образованиях. Например, отчётные данные по Оренбургу получены как сумма объёма выбросов по городскому округу «Город Оренбург» и Оренбургскому муниципальному району.

Вторая особенность в том, что отчётность обычно содержит только информацию о выбросах со стационарных источников, в то время как некоторая часть диоксида серы поступает с передвижных источников. Однако передвижные источники отражены в отчётности ещё хуже, чем стационарные. При составлении каталога использовались только данные по стационарным источникам. В подавляющем большинстве случаев это не должно приводить к большим расхождениям, потому что при наличии крупного источника выбросов в крупном промышленном центре вклад выбросов от автотранспорта в общий объём выбросов пренебрежительно мал. Однако в некоторых случаях о наличии передвижных источников выбросов не стоит забывать — например, если речь идёт о выбросах в Москве, где вклад автотранспорта превышает вклад стационарных источников.

Таким образом, для исследования использовались два набора данных: 450 значений для 30 источников выбросов за 15  с 2005 по 2019 год и 251 значение для 30 источников выбросов за разные годы в пределах того же периода в 15 лет. Данные были проанализированы с использованием методов статистического анализа. Анализ проводится с помощью языка программирования R и среды разработки RStudio. Все исходные данные и программный код для анализа находятся у автора статьи и могут быть предоставлены по запросу.

## 2.2. Анализ данных

## 2.3. Обсуждение результатов анализа

# 3. Выводы

## Библиография